services:
  - type: web
    name: bestie_backend
    runtime: python
    plan: starter
    region: oregon
    autoDeploy: true
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REDIS_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: worker
    name: bestie_worker
    runtime: python
    plan: starter
    region: oregon
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.worker_entry
    envVars:
      - key: REDIS_URL
        sync: false
      - key: QUEUE_NAME
        value: bestie_queue
      - key: WORKER_HEARTBEAT_SEC
        value: "10"      # launch: chatty; later bump to 30
      - key: WORKER_JOB_TIMEOUT
        value: "240"     # GPT + Vision + Whisper buffer
      - key: WORKER_RESULT_TTL
        value: "900"     # keep results 15 min for debugging
      - key: ENABLE_RQ_SCHEDULER
        value: "0"       # use Render Cron instead

cronJobs:
  - name: reengage-users
    schedule: "0 15 * * *"     # 15:00 UTC ≈ 9:00am Denver (summer)
    httpMethod: POST
    url: https://bestie-backend.onrender.com/jobs/reengage
    headers:
      - name: X-Cron-Secret
        value: ${CRON_SECRET}

  - name: plan-rollover
    schedule: "0 7 * * *"      # daily 07:00 UTC
    httpMethod: POST
    url: https://bestie-backend.onrender.com/tasks/plan_rollover
    headers:
      - name: X-Cron-Secret
        value: ${CRON_SECRET}
