services:
  - type: web
    name: bestie-backend
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

  - type: worker
    name: bestie-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app/start_worker.py
